# This is a basic workflow to help you get started with Actions

name: Collect_PD_Stats

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]



# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup R
        uses: r-lib/actions/setup-R@v1
        with:
          r-version: '3.5.3' # The R version to download (if necessary) and use.
      - name: do stuff
        run: Rscript -e 'print("hello")'
