name: Monitor page over time

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/8 * * *"

jobs:
  page2pdf:
    runs-on: ubuntu-latest
    name: page2pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
         echo $PWD
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://canada.ca/en/government/system/digital-government/digital-government-innovations/enabling-interoperability/gc-enterprise-data-reference-standards
          destination: screenshot.png
          full-page: true
      - run: |
          curl https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/enabling-interoperability/gc-enterprise-data-reference-standards.html -O gc-enterprise-data-reference-standards.html 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push -f origin master
