name: Monitor page over time

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/8 * * *"

jobs:
  page2pdf:
    runs-on: ubuntu-latest
    name: page2pdf
    steps:
      - uses: actions/checkout@v2
      - id: page2pdf
        uses: ./
        with:
          url: 'https://canada.ca/en/government/system/digital-government/digital-government-innovations/enabling-interoperability/gc-enterprise-data-reference-standards'
      - name: page2pdf output
        run: echo "domain was ${{ steps.page2pdf.outputs.domain }}"
