name: Update News CSV

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 7:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run update script
        run: python update_news.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add combined_news.csv
          git commit -m 'Update combined news CSV'
          git push
       
